app/Http/routes.php
<?php

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::group(['namespace' => 'Arsip'], function () {
    Route::resource('module', 'ModuleController', ['only' => ['index']]);
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);

    Route::post('outbox/grid', [
        'as' => 'outbox.grid',
        'uses' => 'OutboxController@grid'
    ]);

    Route::get('outbox/upload', [
        'as' => 'outbox.upload',
        'uses' => 'OutboxController@upload'
    ]);

    Route::get('outbox/bagian/{id}', [
        'as' => 'outbox.bagian',
        'uses' => 'OutboxController@bagian'
    ])->where('id', '[0-9]+');

    Route::post('outbox/bagian', [
        'as' => 'outbox.bagian-store',
        'uses' => 'OutboxController@bagianCreate'
    ]);

    Route::resource('outbox', 'OutboxController');
});

app/Outbox.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Outbox extends Model {

    protected $table = 'outbox';

    public function getDates()
    {
        return ['tanggal_surat'];
    }

    public function scopeSearch($q, $filter)
    {
        return $q->where(function($query) use ($filter) {
            if ($filter['nomor_surat']) $query->where('nomor_surat', 'LIKE', '%'.$filter['nomor_surat'].'%');
            if ($filter['dari_tanggal']) {
                if ($filter['sampai_tanggal']) {
                    $query->whereBetween('tanggal_surat', [$this->castDate($filter['dari_tanggal']), $this->castDate($filter['sampai_tanggal'])]);
                } else {
                    $query->where('tanggal_surat', $this->castDate($filter['dari_tanggal']));
                }
            }
            if ($filter['jenis_id']) $query->where('jenis_id', $filter['jenis_id']);
            if ($filter['kepentingan_id']) $query->where('kepentingan_id', $filter['kepentingan_id']);
            if ($filter['kerahasiaan_id']) $query->where('kerahasiaan_id', $filter['kerahasiaan_id']);
            if ($filter['perihal']) $query->where('perihal', "LIKE", '%'.$filter['perihal'].'%');
        });
    }

    public function inbox()
    {
        return $this->hasOne('App\Inbox');
    }

    public function jenis()
    {
        return $this->belongsTo('App\JenisSurat', 'jenis_id');
    }

    public function rahasia()
    {
        return $this->belongsTo('App\Kerahasiaan', 'kerahasiaan_id');
    }

    public function penting()
    {
        return $this->belongsTo('App\Kepentingan', 'kepentingan_id');
    }

    public function lingkup()
    {
        return $this->belongsTo('App\RuangLingkup', 'lingkup_id');
    }

    public function toBagian()
    {
        return $this->belongsTo('App\Bagian', 'to_bagian_id');
    }

    public function fromBagian()
    {
        return $this->belongsTo('App\Bagian', 'from_bagian_id');
    }

    private function castDate($date) {
        return Carbon::createFromFormat('d F Y', $date)->toDateString();
    }
}

app/Http/Controllers/Arsip/DashboardController.php
<?php  namespace App\Http\Controllers\Arsip;

use App\Http\Controllers\Controller;

class DashboardController extends Controller {
    public function index()
    {
        return view('arsip.dashboard.index');
    }
}

app/Http/Controllers/Arsip/ModuleController.php
<?php  namespace App\Http\Controllers\Arsip;

use App\Http\Controllers\Controller;

class ModuleController extends Controller {
    public function index()
    {
        return view('arsip.layouts.default');
    }
}

app/Http/Controllers/Arsip/OutboxController.php
<?php  namespace App\Http\Controllers\Arsip; 

use App\Bagian;
use App\Forms\OutboxForm;
use App\Http\Controllers\Controller;
use App\Outbox;
use Illuminate\Http\Request;

class OutboxController extends Controller {
    public function index(OutboxForm $form)
    {
        return view('arsip.outbox.index')->with('form', $form);
    }

    public function grid(Outbox $outbox, Request $request)
    {
        $filter = $request->all();

        $result = $outbox->search($filter)->paginate(15);

        return view('arsip.outbox._grid')->with('outbox', $result);
    }

    public function show($id)
    {
        return "YOOO";
    }

    public function create(OutboxForm $form)
    {
        return view('arsip.outbox._form_add')->with('form', $form);
    }

    public function upload()
    {
        return view('arsip.outbox._form_upload');
    }

    public function bagian($id)
    {
        $bagian = Bagian::take(10)->get(['id', 'kode', 'nama']);

        return view('arsip.outbox._form_bagian')->with('bagian', $bagian);
    }

    public function bagianCreate(Request $request)
    {
        $bagian = $request->all();

        dd($bagian);
    }
}

resources/views/arsip/outbox/_form_add.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Tambah Dokumen</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['role' => 'form', 'id' => 'filter-outbox']) !!}
            <div class="form-body">
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-md-3">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::text('nomor_surat', '', ['class'=>'form-control']) !!}
                            {!! Form::label('nomor_surat', 'Nomor Surat') !!}
                        </div>
                    </div>
                    <div class="col-md-3 col-md-offset-3">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::text('tanggal_surat', '', ['class'=>'form-control date-picker', 'style'=>'text-align:center;']) !!}
                            {!! Form::label('tanggal_surat', 'Tanggal Surat') !!}
                        </div>
                    </div>
                </div>
                <div class="row"style="margin-bottom: 10px;">
                    <div class="col-md-10">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::text('perihal', '', ['class'=>'form-control']) !!}
                            {!! Form::label('perihal', 'Perihal') !!}
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::select('jenis_id', $form->options('JenisSurat'), '', ['class' => 'form-control']) !!}
                            {!! Form::label('jenis_id', 'Jenis Surat') !!}
                        </div>
                    </div>
                    <div class="col-md-4 col-md-offset-2">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::select('lingkup_id', $form->options('RuangLingkup'), '', ['class' => 'form-control']) !!}
                            {!! Form::label('lingkup_id', 'Ruang Lingkup') !!}
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::select('kepentingan_id', $form->options('Kepentingan'), '', ['class' => 'form-control']) !!}
                            {!! Form::label('kepentingan_id', 'Kepentingan') !!}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            {!! Form::select('kerahasiaan_id', $form->options('Kerahasiaan'), '', ['class' => 'form-control']) !!}
                            {!! Form::label('kerahasiaan_id', 'Kerahasiaan') !!}
                        </div>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">TUTUP</button>
    <button type="button" class="btn blue">SIMPAN</button>
</div>

<script>
    $('.date-picker').datepicker({
        format: 'dd MM yyyy',
        orientation: "left",
        autoclose: true
    });
</script>

resources/views/arsip/outbox/_form_bagian.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Pilih Bagian</h4>
</div>
{!! Form::open(['role' => 'form', 'id' => 'bagian-outbox']) !!}
{!! Form::hidden('id', $outbox->id) !!}
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">

            <div class="form-body">
                <div class="form-group form-md-checkboxes">
                    <label>Bagian Yang Akan Dikirimkan Dokumen</label>
                    <div class="md-checkbox-list">
                        @foreach($bagian as $row)
                            <div class="md-checkbox">
                                <input type="checkbox" name="{!! $row->id !!}" id="{!! $row->id !!}" class="md-check">
                                <label for="{!! $row->id !!}">
                                    <span></span>
                                    <span class="check"></span>
                                    <span class="box"></span>
                                    {!! $row->nama !!} </label>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">TUTUP</button>
    <button type="submit" class="btn blue">SIMPAN</button>
</div>
{!! Form::close() !!}

<script>
    (function() {
        var Form = function() {
            this.formId = 'form#bagian-outbox';
        };
        Form.prototype.store = function() {
            var self = this;
            $(self.formId).on('submit', function(e) {
                e.preventDefault();

                $.ajax({
                    method: "POST",
                    url: '{!! route("outbox.bagian-store") !!}',
                    data: $(self.formId).serialize()
                }).done(function(html) {
                    console.log(html);
                });
            })
        }

        var f = new Form();

        f.store();
    })();
</script>

resources/views/arsip/outbox/_form_upload.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">UPLOAD DOKUMEN</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <form id="fileupload" action="#" method="POST" enctype="multipart/form-data">
                <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
                <div class="row fileupload-buttonbar">
                    <div class="col-lg-7">
                        <!-- The fileinput-button span is used to style the file input field as button -->
                        <span class="btn green fileinput-button">
                        <i class="fa fa-plus"></i>
                        <span>
                        Tambah File Dokumen... </span>
                        <input type="file" name="files[]" multiple="">
                        </span>
                        <button type="submit" class="btn blue start">
                            <i class="fa fa-upload"></i>
                                        <span>
                                        Mulai Upload </span>
                        </button>
                        <button type="reset" class="btn warning cancel">
                            <i class="fa fa-ban-circle"></i>
                                        <span>
                                        Batalkan Upload </span>
                        </button>
                        <button type="button" class="btn red delete">
                            <i class="fa fa-trash"></i>
                                        <span>
                                        Hapus </span>
                        </button>
                        <!-- The global file processing state -->
                        <span class="fileupload-process">
                        </span>
                    </div>
                    <!-- The global progress information -->
                    <div class="col-lg-5 fileupload-progress fade">
                        <!-- The global progress bar -->
                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar progress-bar-success" style="width:0%;">
                            </div>
                        </div>
                        <!-- The extended global progress information -->
                        <div class="progress-extended">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <!-- The table listing the files available for upload/download -->
                <table role="presentation" class="table table-striped clearfix">
                    <tbody class="files">
                    </tbody>
                </table>
            </form>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Keterangan</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        <li>
                            The maximum file size for uploads in this demo is <strong>5 MB</strong> (default file size is unlimited).
                        </li>
                        <li>
                            Only image files (<strong>JPG, GIF, PNG</strong>) are allowed in this demo (by default there is no file type restriction).
                        </li>
                        <li>
                            Uploaded files will be deleted automatically after <strong>5 minutes</strong> (demo setting).
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">TUTUP</button>
    <button type="button" class="btn blue">SIMPAN</button>
</div>

<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger label label-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn blue start" disabled>
                    <i class="fa fa-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn red cancel">
                    <i class="fa fa-ban"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-download fade">
                <td>
                    <span class="preview">
                        {% if (file.thumbnailUrl) { %}
                            <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                        {% } %}
                    </span>
                </td>
                <td>
                    <p class="name">
                        {% if (file.url) { %}
                            <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                        {% } else { %}
                            <span>{%=file.name%}</span>
                        {% } %}
                    </p>
                    {% if (file.error) { %}
                        <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                    {% } %}
                </td>
                <td>
                    <span class="size">{%=o.formatFileSize(file.size)%}</span>
                </td>
                <td>
                    {% if (file.deleteUrl) { %}
                        <button class="btn red delete btn-sm" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                            <i class="fa fa-trash-o"></i>
                            <span>Delete</span>
                        </button>
                        <input type="checkbox" name="delete" value="1" class="toggle">
                    {% } else { %}
                        <button class="btn yellow cancel btn-sm">
                            <i class="fa fa-ban"></i>
                            <span>Cancel</span>
                        </button>
                    {% } %}
                </td>
            </tr>
        {% } %}
    </script>

<script>
    FormFileUpload.init();
</script>

resources/views/arsip/outbox/_grid.blade.php
<?php
    $n = 1;
?>

<div class="col-md-12">
    <div class="portlet box green">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cogs"></i>DAFTAR DOKUMEN
            </div>
        </div>
        <div class="portlet-body flip-scroll" id="table-surat">
            <div class="btn-group btn-group-solid margin-bottom-10">
                <button type="button" class="btn blue" id="add-outbox">TAMBAH DOKUMEN</button>
            </div>
            @if(sizeof($outbox) > 0)
            <table class="table table-bordered table-striped table-condensed flip-content center-head">
                <thead class="flip-content">
                    <tr>
                        <th>#</th>
                        <th>No. Surat</th>
                        <th>Tgl. Surat</th>
                        <th>Perihal</th>
                        <th>Jenis</th>
                        <th>Kep</th>
                        <th>Rhs</th>
                        <th>Lkp</th>
                        <th>Doc</th>
                        <th colspan="2">Action</th>
                        <th>Bagian</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($outbox as $row)
                    <tr>
                        <td>{!! str_pad($n++, 3, '0', STR_PAD_LEFT); !!}</td>
                        <td>{!! $row->nomor_surat !!}</td>
                        <td>{!! $row->tanggal_surat->format('d F Y') !!}</td>
                        <td>{!! $row->perihal !!}</td>
                        <td class="text-center">
                            <button type="button" class="btn red btn-xs" title="{!! $row->jenis->nama !!}">{!! $row->jenis->kode !!}</button>
                        </td>
                        <td class="text-center">
                            <button type="button" class="btn purple btn-xs" title="{!! $row->penting->nama !!}">{!! $row->penting->kode !!}</button>
                        </td>
                        <td class="text-center">
                            <button type="button" class="btn yellow btn-xs" title="{!! $row->rahasia->nama !!}">{!! $row->rahasia->kode !!}</button>
                        </td>
                        <td class="text-center">
                            <button type="button" class="btn dark btn-xs" title="{!! $row->lingkup->nama !!}">{!! $row->lingkup->kode !!}</button>
                        </td>
                        <td class="text-center"><a href="javascript:;" class="btn btn-icon-only dark" data-upload="true" title="UPLOAD DOKUMEN"><i class="fa fa-upload"></i></a></td>
                        <td class="text-center"><a href="javascript:;" class="btn btn-icon-only green" data-add="true"><i class="fa fa-edit"></i></a></td>
                        <td class="text-center"><a href="javascript:;" class="btn btn-icon-only red"><i class="fa fa-times"></i></a></td>
                        <td class="text-center"><a href="javascript:;" class="btn btn-icon-only blue" data-url="{!! route('outbox.bagian', $row->id) !!}" data-bagian="true"><i class="fa fa-plus" title="Tambah Bagian yang akan dikirim"></i></a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
                <div class="row">
                    <div class="col-md-12 text-center">
                        {!! $outbox->render() !!}
                    </div>
                </div>
            @else
                <div class="alert alert-warning">
                    <strong>Peringatan!</strong> Tidak ditemukan data surat outbox
                </div>
            @endif
        </div>
    </div>
</div>

<div id="ajax-modal" class="modal container fade" tabindex="-1" data-backdrop="static" data-keyboard="false"></div>

<script>
    $('.pagination a').on('click', function (event) {
        event.preventDefault();
        if ( $(this).attr('href') != '#' ) {
            $("html, body").animate({ scrollTop: 0 }, "fast");
            $('#table-surat').load($(this).attr('href'));
        }
    });

    $.fn.modal.defaults.spinner = $.fn.modalmanager.defaults.spinner =
            '<div class="loading-spinner" style="width: 200px; margin-left: -100px;">' +
            '<div class="progress progress-striped active">' +
            '<div class="progress-bar" style="width: 100%;"></div>' +
            '</div>' +
            '</div>';

    $.fn.modalmanager.defaults.resize = true;

    var $modal = $('#ajax-modal');

    $('#add-outbox').on('click', function(){
        $('body').modalmanager('loading');
        setTimeout(function(){
            $modal.load('{!! route("outbox.create") !!}', '', function(){
                $modal.modal();
            });
        }, 500);
    });

    $('[data-upload="true"]').on('click', function() {
        $('body').modalmanager('loading');
        setTimeout(function(){
            $modal.load('{!! route("outbox.upload") !!}', '', function(){
                $modal.modal();
            });
        }, 500);
    });

    $('[data-bagian="true"]').on('click', function() {
        var self = this;
        $('body').modalmanager('loading');
        setTimeout(function(){
            var url = $(self).data('url');
            $modal.load(url, '', function(){
                $modal.modal();
            });
        }, 500);
    });
</script>

resources/views/arsip/outbox/index.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="portlet-title">
                <div class="caption font-green">
                    <i class="icon-pin font-green"></i>
                    <span class="caption-subject bold uppercase"> Filter Dokumen</span>
                </div>
            </div>
            <div class="portlet-body form">
                {!! Form::open(['role' => 'form', 'id' => 'filter-outbox']) !!}
                    <div class="form-body">
                        <div class="row" style="margin-bottom: 25px;">
                            <div class="col-md-3">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::text('nomor_surat', '', ['class'=>'form-control']) !!}
                                    {!! Form::label('nomor_surat', 'Nomor Dokumen') !!}
                                    <span class="help-block">Nomor dokumen yang akan dicari.</span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 25px;">
                            <div class="col-md-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::text('dari_tanggal', '', ['class'=>'form-control date-picker', 'style'=>'text-align:center;']) !!}
                                    {!! Form::label('dari_tanggal', 'Dari Tanggal') !!}
                                    <span class="help-block">Tanggal awal dokumen yang akan dicari.</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::text('sampai_tanggal', '', ['class'=>'form-control date-picker', 'style'=>'text-align:center;']) !!}
                                    {!! Form::label('sampai_tanggal', 'Sampai Tanggal') !!}
                                    <span class="help-block">Tanggal Akhir dokumen yang akan dicari.</span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 25px;">
                            <div class="col-md-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::select('jenis_id', $form->options('JenisSurat'), '', ['class' => 'form-control']) !!}
                                    {!! Form::label('jenis_id', 'Jenis Dokumen') !!}
                                    <span class="help-block">Jenis dokumen yang akan dicari.</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::text('perihal', '', ['class'=>'form-control']) !!}
                                    {!! Form::label('perihal', 'Perihal') !!}
                                    <span class="help-block">Perihal dokumen yang akan dicari.</span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 25px;">
                            <div class="col-md-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::select('kepentingan_id', $form->options('Kepentingan'), '', ['class' => 'form-control']) !!}
                                    {!! Form::label('kepentingan_id', 'Kepentingan') !!}
                                    <span class="help-block">Kepentingan dokumen yang akan dicari.</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    {!! Form::select('kerahasiaan_id', $form->options('Kerahasiaan'), '', ['class' => 'form-control']) !!}
                                    {!! Form::label('kerahasiaan_id', 'Kerahasiaan') !!}
                                    <span class="help-block">Kerahasiaan dokumen yang akan dicari.</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions noborder">
                        <button type="submit" class="btn blue">Submit</button>
                        <button type="button" class="btn default">Batal</button>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

<div class="row" id="content-grid"></div>

<script>
    (function() {
        var Form = function() {
            this.formId = 'form#filter-outbox';
        };
        Form.prototype.fetch = function() {
            var self = this;
            $(self.formId).on('submit', function(e) {
                e.preventDefault();

                $.ajax({
                    method: "POST",
                    url: '{!! route("outbox.grid") !!}',
                    data: $(self.formId).serialize()
                }).done(function(html) {
                    $('#content-grid').html(html);
                });
            })
        }

        var f = new Form();

        f.fetch();

        $('.date-picker').datepicker({
            format: 'dd MM yyyy',
            orientation: "left",
            autoclose: true
        });
    })();
</script>